data:
  dataset: cifar10_3_5
  normalize: False
  train_size: 1000
  bound_data_size: 1000
  label_noise:
  gpu: 3

model:
  seed: 0
  width: 100
  hidden_layer: 2

train_net:
  lr: 10
  epochs: 300
  solve_ode: True
  eval_interval: 1
  oed_rtol: 1e-5